pid_file /var/run/mosquitto.pid
persistence true
persistence_location /mosquitto/data/
log_dest stdout

allow_anonymous false
password_file /mosquitto/config/passwd

# ACL with pattern-based rules (vulnerable)
# each can user for their topic health/data/<username>
# Client with username="#" or "+" this is avoidaded
acl_file /mosquitto/config/acl.conf